### ISSUE TITLE
equal contributions required

### ISSUE THREAD

**Issue by rachelss** [0evv/bigdata-hw3#5]
@NJBarone2 - I only see 1 commit changing 2 lines. I'm not sure of your contribution to the work.

**Comment by NJBarone2** [comment]
Below is the link to the R script that I had made for Figure 2, Weight vs Sex Over Time.  Then, the 2 line commit you had mentioned would have been the final edit of the two paragraph description for Figure 2.  https://github.com/NJBarone2/bigdata-hw3/pull/2/commits/95a557367ec547c2078a0c3cf501ffe09bb303c2

**Comment by rachelss** [comment]
@NJBarone2 You didn't actually submit a pull request for this graph to the main repository and it looks like Elliot did a similar graph. Update your repo with all of Elliot's and Sam's changes, add a new graph, push it, and submit a pull request to Elliot.

**Comment by NJBarone2** [comment]
It seemed as if I never merged my commit.  My apologies.

**Comment by rachelss** [comment]
@NJBarone2 please add an analysis asap
